name: AQI Training Pipeline

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  model_training:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Train AQI Forecasting Model
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          python src/training/train_from_feature_store.py